<<<<<<< Updated upstream
name: ReportWebhook
version: 1.0.0
main: com.tuo.plugin.ReportWebhook
=======
name: ReportWebhookPaperDB
version: 1.1.0
main: com.example.reportplugin.ReportPlugin
>>>>>>> Stashed changes
api-version: "1.21"
commands:
  report:
    description: Segnala un giocatore allo staff
    usage: /report <giocatore> <motivo>
<<<<<<< Updated upstream
=======
  reports:
    description: Mostra i tuoi report
    usage: /reports
  staffreports:
    description: Gestisci i report
    usage: /staffreports [id] <confirm|decline>
permissions:
  report.use:
    description: Permette di usare /report e /reports
    default: true
  report.staff:
    description: Permette di usare /staffreports
    default: op
>>>>>>> Stashed changes
