name: ReportWebhookPaperDB
version: 1.1.0
main: com.example.reportplugin.ReportPlugin
api-version: "1.13"
commands:
  report:
    description: Segnala un giocatore
    usage: /report <giocatore> <motivo>
  reports:
    description: Mostra i tuoi report
    usage: /reports
  staffreports:
    description: Gestisci i report
  usage: /staffreports [id] <confirm|decline|remove>
permissions:
  report.use:
    description: Permette di usare /report e /reports
    default: true
  report.staff:
    description: Permette di usare /staffreports
    default: op
